#!/bin/bash

set -o errexit
set -o pipefail

if [[ -z "${KUBERNETES_SERVICE_HOST}" ]]; then
    uvicorn src.app.main:app --host 0.0.0.0 --port 8000 --reload
else
    uvicorn src.app.main:app --proxy-headers --host 0.0.0.0 --port 8000
fi